### ISSUE TITLE
Fatal error pressing csv file button

### ISSUE THREAD

**Issue by Volker2014** [markocupic/import_from_csv#4]
Hello Marko,

i tried this extension, but if i press the csv file button, then i get this fatal error message:
Fatal error: Class 'ImportFromCsvModel' not found in .../system/modules/core/controllers/BackendFile.php on line 87

Any idea, what is going wrong here?

Best regards
Volker

**Comment by markocupic** [comment]
Hallo Volker
Du kannst mal testen. Die neue Version ist im ER.
Lg Marko

**Comment by Volker2014** [comment]
Hallo Marko,

es sieht so aus, als hättest Du vergessen, die Datei ImportFromCsvModel.php einzuchecken.

LG Volker

**Comment by markocupic** [comment]
Jetzt passts.

**Comment by Volker2014** [comment]
Super. Danke für die schnelle Hilfe.
Ich benutze den Composer. Kannst Du bei Gelegenheit die neue Version bereitstellen?

**Comment by markocupic** [comment]
Hallo Volker
Die Erweiterung sollte nun Composer tauglich sein. Kannst du das mal testen, da ich immer noch nicht damit arbeite.
Bin froh, um eine kurze Rückmeldung.
Liebe Grüsse
Marko

**Comment by Volker2014** [comment]
Hallo Marko,

die neue Version 9025 lässt sich installieren und funktioniert auch.

Ich habe noch eine Idee für eine Verbesserung: Eine Summary am Anfang des Reports wäre hilfreich, in der Art: x Ok, y Error.

Gruß
Volker

**Comment by markocupic** [comment]
@Volker2014 
Summary ist in der neusten Version eingebaut.
Liebe Grüsse
Marko

**Comment by Volker2014** [comment]
Summary funktioniert. Ist sehr hilfreich, da ich einige Fehler dadurch gefunden habe. Danke
