### ISSUE TITLE
Versuch automatische Koordinatenberechnung einzubauen

### ISSUE THREAD

**Issue by design23** [markocupic/import_from_csv#5]
Hi Marko,

erstmal danke für die tolle Erweiterung! Funktioniert soweit super.
Ich versuche derzeit einen Import hinzubekommen, bei dem bereits während des Importvorgangs automatisch Geokoordinaten aus einem Adressfeld berechnet werden sollen. Zieltabelle ist ein Metamodel. Dazu habe ich (da ich nicht weiß ob und wie man den Hook verwenden muss) direkt in der ImportFromCsv.php was dazugedichtet:

Ab Zeile 260: 

if($strTable == 'mm_dealers' && $set['mm_dealer_address'] != '')
{
   $strAddress = $set['mm_dealer_address'];                                   
   $strAddress = preg_replace( "/\r|\n/", ", ", $strAddress );
   $calCoords = \delahaye\GeoCode::getCoordinates($strAddress, '', '');   
   $set['mm_dealer_geolocation'] = $calCoords;
}

Ich bediene mich dabei der Erweiterung dlh_geocode...
Das spannende ist, dass die Bereichnung teilweise funktioniert. Aber jedesmal wenn ich den gleichen Import wiederhole, fehlen bei unterschiedlichen Einträgen die Koordinaten.
Hättest Du da vielleicht eine Idee woran das liegen könnte, bzw. einen Denkanstoß? Bin ich hier komplett auf dem Holzweg?

**Comment by design23** [comment]
Ich muss meine Frage zurückziehen. Mittlerweile habe ich rausgefunden, dass es an der Google API lag.  Die Anfragen für die Koordinatenberechnung kamen zu schnell. Habe eine Verzögerung eingebaut und nun funktioniert das wie gewünscht.

**Comment by markocupic** [comment]
Super,  schön, wenn das Modul gebraucht wird. Machst du die Anpassung nun mit dem Hook? 
Lg Marko

**Comment by design23** [comment]
Nein, da ich wie gesagt nicht verstanden habe, wie das Ding funktioniert. Fixe Texte konnte ich damit einbauen, aber Variablen gingen irgendwie nicht. Hast Du da eine Anleitung für Doofe? ^^

**Comment by markocupic** [comment]
Hast du die Beschreibung gelesen?
https://github.com/markocupic/import_from_csv/issues/5#issuecomment-76201676
nach unten scrollen.
Das ganze funktioniert so wie bei allen Hooks in Contao, Du erstellst im Modulverzeichnis einen neuen Order. In der config/config.php registrierst du den Hook. Und in der selber erstellten Klasse in classes/MyCsvImportHook.php baust du die Logik ein. 
Vergiss nicht, wenn du alles auf den Server geladen hast die config/autoload.php aus dem Backend heraus generieren zu lassen.

Übrigens habe ich in der config.php und im classes-Verzeichnis meiner Erweiterung bereits ein mögliches Szenario/Beispiel eingebaut. In der config.php ist die Registrierung des Hooks aber auskommentiert. Da kannst du mal abgucken, wie das gehen könnte. Ich empfehle dir aber unbedingt ein neues Verzeichnis zu erstellen, damit das alles updatesicher bleibt.

Wenn du es nicht auf die Reihe kriegst, dann schick mir mal die von dir eingebaute Logik. meien email-Adresse findest du im Quellcode der Erweiterung.

Liebe Grüsse

Marko
