### ISSUE TITLE
Daten-Validierung

### ISSUE THREAD

**Issue by xantippe** [markocupic/import_from_csv#6]
Hi,

in dem Hook-Beispiel würden m.E. alle Vornamen und Nachnamen den selben Inhalt (Bruce Springsteen) bekommen... wie erhalte ich Zugriff auf den Ursprüglichen Wert der "CSV-Zelle"? Validierung bedeutet doch in dem Zusammenhang "Überprüfung" - oder?

Welche Möglichkeiten bietet das Tool, wenn eine Überprüfung fehl schlägt (Abbruch, weiter, Fehlermeldung)?

Gibt es eine Vorab-Prüfung bzw. Validierung - also bevor angefangen wird, die Daten ind die Tabelle zu schaufeln?

Gruss

**Comment by markocupic** [comment]
Hallo xantippe
Habe die Klasse noch etwas angepasst. Schau nochmals im hier: https://github.com/markocupic/import_from_csv im README Abschnitt, ob du dahinter kommst.

Fehlermeldungen sind möglich, Auch ist es möglich den INSERT zu unterbrechen, wenn Fehler bei der benutzerspezifischen Validierung auftreten. Schau dir das $arrCustomValidation Array in der Validierungsmethode des Beispiels genau an. 
Melde dich wieder, wenn es nciht klar ist.

Liebe Grüsse

Marko

**Comment by design23** [comment]
Hi Marko,

ich schließe mich mal hier kurz an.
Kann man mit der Validierung auch eigene Werte eintragen?
Falls Du Dich erinnerst, wir hatten bei einer älteren Version mal Kontakt. Mein Vorhaben damals war, Geokoordinaten innerhalb des Imports zu berrechnen und direkt einzutragen.
Aber irgendwie krieg ich das mit der aktuellsten Version nicht gebacken.

**Comment by markocupic** [comment]
Was möchtest du denn genau machen? 
Liebe Grüsse 
Marko

**Comment by design23** [comment]
Es gibt u.a. 2 Felder für eine Adresse. Feld 1 für Straße + Hausnummer, Feld 2 für PLZ und Ort.
Daraus soll ein drittes Feld "Geolocation" berechnet werden. Und das eben direkt beim Import.

Was ich versucht habe:

public function addGeolocation($arrCustomValidation, $objBackendModule = null)
    {
        if($arrCustomValidation['strTable'] == 'retailer'){

            if($arrCustomValidation['fieldname'] == 'street'){
                $strStreet = $arrCustomValidation['value'];
            }
            
            if($arrCustomValidation['fieldname'] == 'city'){
                $strCity = $arrCustomValidation['value'];
            }

            $strAddress = $strStreet.', '.$strCity;
            
            if($arrCustomValidation['fieldname'] == 'geolocation')
            {
                $calCoords = \delahaye\GeoCode::getCoordinates($strAddress, '', '');
                $arrCustomValidation['arrayLine'] = $calCoords;
            }

        }

        return $arrCustomValidation;
    }

**Comment by markocupic** [comment]
Bin gerade in den Ferien. Aber ich sehe, was du falsch machst. 
Schau mal das Array $arrCustomValidation['arrayLine'] an. Hier findest du die Strasse und die PLZ des aktuellen Datesatzes. 
Das Beispiel in der README hast du gesehen? Wenn du das Problem bis am Abend nicht gelöst hast, melde dich. 
Am Smartphone ist das etwas schwierig. Am Aben kann ich dir das am Notebook zeigen.
Lg Marko

**Comment by design23** [comment]
Die Werte sehe ich, aber was brauchbares daraus stricken, funktioniert irgendwie nicht.
Stehe scheinbar komplett auf dem Schlauch...

    public function addGeolocation($arrCustomValidation, $objBackendModule = null)
    {
        // DEALER - DE
        if($arrCustomValidation['strTable'] == 'retailer'){

            if($arrCustomValidation['fieldname'] == 'street'){
                $strStreet = $arrCustomValidation['arrayLine']['street'];
            }
            
            if($arrCustomValidation['fieldname'] == 'city'){
                $strCity = $arrCustomValidation['arrayLine']['city'];
            }

            $strAddress = $strStreet.', '.$strCity;
            
            if($arrCustomValidation['fieldname'] == 'geolocation')
            {
                $calCoords = \delahaye\GeoCode::getCoordinates($strAddress, '', '');
                $arrCustomValidation['value'] = $calCoords;
            }

        }

        return $arrCustomValidation;
    }

**Comment by design23** [comment]
Kommando zurück!
Hab's jetzt. Der ganze Spaß muss natürlich wie folgt aussehen (falls das mal jemand brauchen kann):

    public function addGeolocation($arrCustomValidation, $objBackendModule = null)
    {

        if($arrCustomValidation['strTable'] == 'retailer'){
            
            if($arrCustomValidation['fieldname'] == 'geolocation')
            {
                $strStreet = $arrCustomValidation['arrayLine']['street'];
                $strCity = $arrCustomValidation['arrayLine']['city'];
                $strAddress = $strStreet.', '.$strCity;
                $calCoords = \delahaye\GeoCode::getCoordinates($strAddress, '', '');
                $arrCustomValidation['value'] = $calCoords;
            }

        }

        return $arrCustomValidation;
    }

**Comment by markocupic** [comment]
Genau! Schön, dass es geklappt hat.
Liebe Grüsse 
Marko

**Comment by markocupic** [comment]
Hallo design23
Habe das Modul noch ein wenig überarbeitet. Lade dir die aktuelle Version aus dem repo runter. Den Beispiel-Hook in der Readme habe ich an deine Problemstellung angepasst, weil ich die Geolocation-Sache als ein sehr typisches und gutes Beispiel erachte. Allerdings ohne Abhängigkeit zu einem anderen Contao-Modul. 
Achte noch darauf, in deiner Methode  $arrCustomValidation['skipWidgetValidation'] auf true zu setzen. Siehe Beispiel in https://github.com/markocupic/import_from_csv
```php
$arrCustomValidation['skipWidgetValidation'] = true;
```

Liebe Grüsse

Marko

**Comment by design23** [comment]
Ah, die Berechnung erfolgt hier quasi ohne dlh_geocode...
Nette Sache, danke dafür.

Kleine Anmerkung am Rande: Ich habe mit diesem Import die Erfahrung gemacht, dass die Abfragen unter gewissen Umständen zu schnell für Googles Geschmack ablaufen. Hatte teilweise Probleme beim Import von 400 Datensätzen aufwärts, weil die Abfragen zu schnell ankamen und die Google API dann sperrt. Um das etwas auszubremsen habe ich dann kurzerhand ein usleep(25000) eingebaut... nicht schön, aber funktioniert. ;-) 
Vielleicht gibt es dafür eine elegantere Lösung, die ich übersehen habe.

**Comment by xantippe** [comment]
@markocupic 

ein "vielgefragtes" Beispiel dürfte der Import von Mitgliedern inkl. der Umwandlung eines "Klartext-Passwortes" zum "Contao-Passwort" sein...

**Comment by markocupic** [comment]
@xantippe 
Dein Importvorhaben lässt sich ziemlich sicher ohne Hooks realisieren. Das Passwort kannst du in der  csv-Datei als Klartext hinterlegen. Es wird beim Import automatisch verschlüsselt. Schau dir im Verzeichnis import_from_csv/csv die mitgelieferte csv-Beispieldatei an. Auf dieser kannst du aufbauen. Wichtig ist lediglich, dass du die Datei im utf-8 Format abspeicherst. Notepad++ kann sowas. Wenn du weitere Fragen hast, melde dich unter m.cupic(ät)gmx.ch
LIebe Grüsse
Marko
