### ISSUE TITLE
Password-Algorithmus

### ISSUE THREAD

**Issue by pswerbung** [markocupic/import_from_csv#7]
Wie kann ich Members in tl_members importieren bezüglich dem Passwort: mit welcher Methode muss es kodiert werden? Oder soll es Plaintext sein? Im Test ging es nicht mit Plaintext oder SHA-1 …

**Comment by markocupic** [comment]
Habe das schnell getestet unter contao 3.5:
Import eines Mitglieds nach tl_member hat problemlos geklappt. Auch das anschliessende Login. Hast du die Beispieldatei gesehen? Sie befindet sich hier: https://github.com/markocupic/import_from_csv/tree/master/csv

Habe aber bemerkt, dass der Import den Vornamen nicht setzt. Schaue das am Abend mal genauer an.
Lg Marko

**Comment by markocupic** [comment]
Nachtrag:
Das Passwortencoding übernimmt in Contao folgende Klasse/Methode.
\Encryption::hash($varInput)

**Comment by pswerbung** [comment]
Danke für die Tipps. Wir werden es im Kundenprojekt nochmals anschauen ;-)
